'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos
Imports Infoware.Reglas.General



#Region "Compra"
Public Class Compra

  Const _Procedimiento As String = "proc_Compra"



  Private mMovimientoInventario As MovimientoInventario = Nothing

  Private mProveedor As Proveedor = Nothing

  Private mTipomovimientocompraventa As TipoMovimientoCompraVenta = Nothing

  Private mPardetTipoCompra As WWTSParametroDet = Nothing

  Private mSucursal As Sucursal = Nothing

  Private mPardetTipoPago As WWTSParametroDet = Nothing

  Private mPardetTipoDireccion As WWTSParametroDet = Nothing

  Public Sub New(ByVal _Empresa As Empresa, ByVal _EsNuevo As Boolean)
    MyBase.New()
    OperadorDatos = _Empresa.OperadorDatos
    Empres_Codigo = _Empresa.Empres_Codigo
    EsNuevo = _EsNuevo
  End Sub

  Public Sub New(ByVal _Sucursal As Sucursal, ByVal _Pardet_TipoCompra As Enumerados.enumTipoCompra, ByVal _EsNuevo As Boolean)
    MyBase.New()
    OperadorDatos = _Sucursal.OperadorDatos
    Sucursal = _Sucursal
    Pardet_TipoCompra = _Pardet_TipoCompra
    EsNuevo = _EsNuevo
  End Sub

  Public Sub New(ByVal _Sucursal As Sucursal, ByVal _PardetTipoCompra As WWTSParametroDet, ByVal _Compra_Numero As Integer)
    Me.New(_Sucursal, _PardetTipoCompra.Pardet_Secuencia, False)
    Compra_Numero = _Compra_Numero
    If Me.Recargar Then
    Else
      Throw New System.Exception("No se puede cargar objeto Compra")
    End If
  End Sub

  Public Sub New(ByVal _Sucursal As Sucursal, ByVal _PardetTipoMovinv As WWTSParametroDet, ByVal _Movinv_Secuencia As Integer, ByVal _estricto As Boolean)
    MyBase.New()
    OperadorDatos = _Sucursal.OperadorDatos
    Sucursal = _Sucursal
    Parame_Tipomovinv = _PardetTipoMovinv.Parame_Codigo
    Pardet_Tipomovinv = _PardetTipoMovinv.Pardet_Secuencia
    Movinv_Secuencia = _Movinv_Secuencia
    If Me.RecargarporMovimientoInventario Then
    Else
      If _estricto Then
        Throw New System.Exception("No se puede cargar objeto Compra")
      End If
    End If
  End Sub

  Public ReadOnly Property Establecimiento() As String
    Get
      Return Left(Compra_Numero, 3)
    End Get
  End Property

  Public ReadOnly Property PuntoEmision() As String
    Get
      Return Me.Compra_Numero.Substring(4, 3)
    End Get
  End Property

  Public ReadOnly Property Secuencial() As String
    Get
      Return Me.Compra_Numero.Substring(8, 7)
    End Get
  End Property

  Public Overridable Shadows Property Pardet_TipoCompraEnum() As Enumerados.enumTipoCompra
    Get
      Return CType(Pardet_TipoCompra, Enumerados.enumTipoCompra)
    End Get
    Set(ByVal value As Enumerados.enumTipoCompra)
      Parame_TipoCompra = CInt(Enumerados.EnumParametros.TipoCompra)
      Pardet_TipoCompra = CInt(value)
    End Set
  End Property

  'WWTSParametroDet
  Public Overridable Property PardetTipoCompra() As WWTSParametroDet
    Get
      If Me.mPardetTipocompra Is Nothing AndAlso Pardet_TipoCompra > 0 Then
        Me.mPardetTipocompra = New WWTSParametroDet(OperadorDatos, Parame_TipoCompra, Pardet_TipoCompra)
      End If
      Return Me.mPardetTipoCompra
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mPardetTipoCompra = value
      Parame_TipoCompra = value.Parame_Codigo
      Pardet_TipoCompra = value.Pardet_Secuencia
    End Set
  End Property

  'Sucursal
  Public Overridable Property Sucursal() As Sucursal
    Get
      If Me.mSucursal Is Nothing AndAlso Sucurs_Codigo > 0 Then
        Me.mSucursal = New Sucursal(New Empresa(OperadorDatos, Empres_Codigo), Sucurs_Codigo)
      End If
      Return Me.mSucursal
    End Get
    Set(ByVal value As Sucursal)
      Me.mSucursal = value
      Empres_Codigo = value.Empres_Codigo
      Sucurs_Codigo = value.Sucurs_Codigo
    End Set
  End Property

  'MovimientoInventario
  Public Overridable Property MovimientoInventario() As MovimientoInventario
    Get
      If Me.mMovimientoInventario Is Nothing AndAlso Movinv_Secuencia > 0 Then
        Me.mMovimientoInventario = New MovimientoInventario(New Sucursal(New Empresa(OperadorDatos, Empres_Codigo), Sucurs_Codigo), Enumerados.enumTipoMovInv.Compra, Movinv_Secuencia)
        mMovimientoInventario.Compra = Me
      End If
      Return Me.mMovimientoInventario
    End Get
    Set(ByVal value As MovimientoInventario)
      Me.mMovimientoInventario = value
      Parame_Tipomovinv = value.Parame_Tipomovinv
      Pardet_TipoMovinv = value.Pardet_Tipomovinv
      Empres_Codigo = value.Empres_Bodega
      Sucurs_Codigo = value.Sucurs_Bodega
      Movinv_Secuencia = value.Movinv_Secuencia
    End Set
  End Property

  'Proveedor
  Public Overridable Property Proveedor() As Proveedor
    Get
      If Me.mProveedor Is Nothing AndAlso Entida_Proveedor > 0 Then
        Me.mProveedor = New Proveedor(OperadorDatos, Entida_Proveedor)
      End If
      Return Me.mProveedor
    End Get
    Set(ByVal value As Proveedor)
      Me.mProveedor = value
      Entida_Proveedor = value.Entida_Codigo
    End Set
  End Property

  'Tipomovimientocompraventa
  Public Overridable Property Tipomovimientocompraventa() As TipoMovimientoCompraVenta
    Get
      If Me.mTipomovimientocompraventa Is Nothing Then
        Me.mTipomovimientocompraventa = New TipoMovimientoCompraVenta(OperadorDatos, Me.Parame_TipoCompra, Pardet_TipoCompra, Empres_Codigo, Sucurs_Codigo)
      End If
      Return Me.mTipomovimientocompraventa
    End Get
    Set(ByVal value As TipoMovimientoCompraVenta)
      Me.mTipomovimientocompraventa = value
      Parame_TipoCompra = value.Parame_TipoCompraVenta
      Pardet_TipoCompra = value.Pardet_TipoCompraVenta
      Empres_Codigo = value.Empres_Codigo
      Sucurs_Codigo = value.Sucurs_Codigo
    End Set
  End Property

  'WWTSParametroDet
  Public Overridable Property PardetTipoPago() As WWTSParametroDet
    Get
      If Me.mPardetTipoPago Is Nothing AndAlso Pardet_TipoPago > 0 Then
        Me.mPardetTipoPago = New WWTSParametroDet(OperadorDatos, Parame_TipoPago, Pardet_TipoPago)
      End If
      Return Me.mPardetTipoPago
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mPardetTipoPago = value
      Parame_TipoPago = value.Parame_Codigo
      Pardet_TipoPago = value.Pardet_Secuencia
    End Set
  End Property

  'WWTSParametroDet
  Public Overridable Property PardetTipoDireccion() As WWTSParametroDet
    Get
      If Me.mPardetTipoDireccion Is Nothing AndAlso Pardet_Tipodireccion > 0 Then
        Me.mPardetTipoDireccion = New WWTSParametroDet(OperadorDatos, Parame_Tipodireccion, Pardet_Tipodireccion)
      End If
      Return Me.mPardetTipoDireccion
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mPardetTipoDireccion = value
      Parame_Tipodireccion = value.Parame_Codigo
      Pardet_Tipodireccion = value.Pardet_Secuencia
    End Set
  End Property

  Public ReadOnly Property FechaVencimiento() As DateTime
    Get
      If PardetTipoPago Is Nothing OrElse MovimientoInventario Is Nothing Then
        Return Now.Date
      Else
        Return mMovimientoInventario.Movinv_Fecha.AddDays(mPardetTipoPago.Pardet_DatoInt1)
      End If
    End Get
  End Property

  Public ReadOnly Property DireccionString() As String
    Get
      Try
        Dim _direccion As New EntidadDireccion(OperadorDatos, Me.Entida_Proveedor, PardetTipoDireccion)
        Return _direccion.Descripcion
      Catch ex As Exception
        Return String.Empty
      End Try
    End Get
  End Property

  Public ReadOnly Property TelefonoString() As String
    Get
      Try
        Return Proveedor.Entidad.Telefono
      Catch ex As Exception
        Return String.Empty
      End Try
    End Get
  End Property

  Public ReadOnly Property CiudadString() As String
    Get
      Try
        Dim _direccion As New EntidadDireccion(OperadorDatos, Me.Entida_Proveedor, PardetTipoDireccion)
        Return _direccion.PardetCiudad.Pardet_Descripcion
      Catch ex As Exception
        Return String.Empty
      End Try
    End Get
  End Property

  Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Empres_Codigo = CType(Fila("Empres_Codigo"), Integer)
    Sucurs_Codigo = CType(Fila("Sucurs_Codigo"), Integer)
    Parame_TipoCompra = CType(Fila("Parame_TipoCompra"), Integer)
    Pardet_TipoCompra = CType(Fila("Pardet_TipoCompra"), Integer)
    Entida_Proveedor = CType(Fila("Entida_Proveedor"), Integer)
    Compra_Numero = CType(Fila("Compra_Numero"), String)
    Parame_Tipomovinv = CType(Fila("Parame_Tipomovinv"), Integer)
    Pardet_TipoMovinv = CType(Fila("Pardet_TipoMovinv"), Integer)
    Movinv_Secuencia = CType(Fila("Movinv_Secuencia"), Integer)
    Parame_TipoPago = CType(Fila("Parame_TipoPago"), Integer)
    Pardet_TipoPago = CType(Fila("Pardet_TipoPago"), Integer)
    Parame_Tipodireccion = CType(Fila("Parame_TipoDireccion"), Integer)
    Pardet_Tipodireccion = CType(Fila("Pardet_TipoDireccion"), Integer)
    SRI_secuencialtransaccion = CStr(Fila("SRI_secuencialtransaccion"))
    SRI_tipocomprobante = CStr(Fila("SRI_tipocomprobante"))
    SRI_creditotributario = CStr(Fila("SRI_creditotributario"))
    Compra_Autorizacion = CStr(Fila("Compra_Autorizacion"))
    Compra_Caducidad = CStr(Fila("Compra_Caducidad"))
    mMovimientoInventario = Nothing
    mProveedor = Nothing
    mTipomovimientocompraventa = Nothing
    mPardetTipoCompra = Nothing
    mPardetTipoPago = Nothing
    mPardetTipoDireccion = Nothing
  End Sub

  Public Overridable Function Recargar() As Boolean
    Dim Result As New DataTable
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "C")
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Parame_TipoCompra", Parame_TipoCompra)
    OperadorDatos.AgregarParametro("@Pardet_TipoCompra", Pardet_TipoCompra)
    OperadorDatos.AgregarParametro("@Entida_Proveedor", Entida_Proveedor)
    OperadorDatos.AgregarParametro("@Compra_Numero", Compra_Numero)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    Try
      Me.MapearDataRowaObjeto(Result.Rows(0))
      EsNuevo = False
      EsModificado = False
    Catch ex As System.Exception
      bReturn = False
    End Try
    Return bReturn
  End Function

  Public Overridable Function RecargarporMovimientoInventario() As Boolean
    Dim Result As New DataTable
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "CM")
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Parame_Tipomovinv", Parame_Tipomovinv)
    OperadorDatos.AgregarParametro("@Pardet_Tipomovinv", Pardet_TipoMovinv)
    OperadorDatos.AgregarParametro("@Movinv_Secuencia", Movinv_Secuencia)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    Try
      Me.MapearDataRowaObjeto(Result.Rows(0))
      EsNuevo = False
      EsModificado = False
    Catch ex As System.Exception
      bReturn = False
    End Try
    Return bReturn
  End Function

  Public Overridable Function Guardar() As Boolean
    If Not EsNuevo And Not EsModificado Then
      Return True
    End If

    Dim Result As Integer = 0
    Dim bReturn As Boolean = True

    OperadorDatos.ComenzarTransaccion()
    bReturn = MovimientoInventario.Guardar

    If bReturn Then
      Empres_Codigo = MovimientoInventario.Empres_Bodega
      Sucurs_Codigo = MovimientoInventario.Sucurs_Bodega
      Parame_Tipomovinv = MovimientoInventario.Parame_Tipomovinv
      Pardet_TipoMovinv = MovimientoInventario.Pardet_Tipomovinv
      Movinv_Secuencia = MovimientoInventario.Movinv_Secuencia
      Dim _fechapago As Date = MovimientoInventario.Movinv_Fecha
      Dim _valorfact As Decimal = MovimientoInventario.TotalGeneral

      Dim sAccion As String = "M"
      If EsNuevo Then
        sAccion = "I"
      End If
      OperadorDatos.AgregarParametro("@accion", sAccion)
      OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
      OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
      OperadorDatos.AgregarParametro("@Parame_TipoCompra", Parame_TipoCompra)
      OperadorDatos.AgregarParametro("@Pardet_TipoCompra", Pardet_TipoCompra)
      OperadorDatos.AgregarParametro("@Entida_Proveedor", Entida_Proveedor)
      OperadorDatos.AgregarParametro("@Compra_Numero", Compra_Numero)
      OperadorDatos.AgregarParametro("@Parame_Tipomovinv", Parame_Tipomovinv)
      OperadorDatos.AgregarParametro("@Pardet_TipoMovinv", Pardet_TipoMovinv)
      OperadorDatos.AgregarParametro("@Movinv_Secuencia", Movinv_Secuencia)
      OperadorDatos.AgregarParametro("@Parame_TipoPago", Parame_TipoPago)
      OperadorDatos.AgregarParametro("@Pardet_TipoPago", Pardet_TipoPago)
      OperadorDatos.AgregarParametro("@SRI_secuencialtransaccion", SRI_secuencialtransaccion)
      OperadorDatos.AgregarParametro("@SRI_tipocomprobante", SRI_tipocomprobante)
      OperadorDatos.AgregarParametro("@SRI_creditotributario", SRI_creditotributario)
      OperadorDatos.AgregarParametro("@Compra_Autorizacion", Compra_Autorizacion)
      OperadorDatos.AgregarParametro("@Compra_Caducidad", Compra_Caducidad)
      OperadorDatos.AgregarParametro("@valorfactura", _valorfact)
      OperadorDatos.AgregarParametro("@fechapago", _fechapago)
      OperadorDatos.AgregarParametro("@Parame_Tipodireccion", Parame_Tipodireccion)
      OperadorDatos.AgregarParametro("@Pardet_Tipodireccion", Pardet_Tipodireccion)
      OperadorDatos.Procedimiento = _Procedimiento
      bReturn = OperadorDatos.Ejecutar(Result)
      OperadorDatos.LimpiarParametros()
      If bReturn Then
        If EsNuevo Then
          Compra_Numero = Result

          'Dim _pago As New PagosDet(Me.MovimientoInventario, True)
          '_pago.Pardet_TipoMovPago = Enumerados.enumTipoMovPagos.Documento
          '_pago.Pagdet_Valor = -Me.MovimientoInventario.TotalGeneral
          '_pago.Pagdet_FechaPago = Me.MovimientoInventario.Movinv_Fecha
          'TODO
          'cambiar la fecha de pago según forma de pago
          'bReturn = _pago.Guardar()

        End If
        If Not OperadorDatos.EstaenTransaccion Then
          EsNuevo = False
          EsModificado = False
        End If
      End If
    End If
    If bReturn Then
      OperadorDatos.TerminarTransaccion()
      AceptarCambios()

      Try
        Proveedor.Entidad.Entida_AutorizacionFactura = Compra_Autorizacion
        Proveedor.Entidad.Entida_CaducidadFactura = Compra_Caducidad
        Proveedor.Guardar()
      Catch ex As Exception

      End Try
    Else
      OperadorDatos.CancelarTransaccion()
    End If
    Return bReturn
  End Function

  Public Overridable Sub AceptarCambios()
    EsNuevo = False
    EsModificado = False

    mMovimientoInventario.AceptarCambios()
  End Sub

  Public Overridable Function Eliminar() As Boolean
    If EsNuevo Then
      Return True
    End If

    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "E")
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Parame_TipoCompra", Parame_TipoCompra)
    OperadorDatos.AgregarParametro("@Pardet_TipoCompra", Pardet_TipoCompra)
    OperadorDatos.AgregarParametro("@Entida_Proveedor", Entida_Proveedor)
    OperadorDatos.AgregarParametro("@Compra_Numero", Compra_Numero)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar
    OperadorDatos.LimpiarParametros()
    Return bReturn
  End Function
End Class
#End Region

#Region "CompraList"
Public Class CompraList
  Inherits System.ComponentModel.BindingList(Of Compra)

  Public Shared Function ObtenerLista(ByVal _Empresa As Empresa, ByVal _Desde As Date, ByVal _Hasta As Date) As CompraList
    Dim oResult As CompraList = New CompraList
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _Empresa.OperadorDatos
      .AgregarParametro("@Accion", "F")
      .AgregarParametro("@Empres_Codigo", _Empresa.Empres_Codigo)
      .AgregarParametro("@fecdesde", _Desde.Date)
      .AgregarParametro("@fechasta", _Hasta.Date.AddDays(1))
      '.AgregarParametro("@Parame_TipoCompra", _PardetTipoCompra.Parame_Codigo)
      '.AgregarParametro("@Pardet_TipoCompra", _PardetTipoCompra.Pardet_Secuencia)
      .Procedimiento = "proc_Compra"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New Compra(_Empresa, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function
End Class
#End Region
