'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos
Imports Infoware.Reglas.General


#Region "EntidadNatural"
Public Class EntidadNatural

  Const _Procedimiento As String = "proc_EntidadNatural"

  Private mEntidad As Entidad = Nothing

  Private mPardetSexo As WWTSParametroDet = Nothing

  Private mPardetEstadoCivil As WWTSParametroDet = Nothing

  Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _EsNuevo As Boolean)
    MyBase.New()
    OperadorDatos = _OperadorDatos
    EsNuevo = _EsNuevo
  End Sub

  Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _Entida_Codigo As Integer)
    Me.New(_OperadorDatos, False)
    Entida_Codigo = _Entida_Codigo
    EsNuevo = Not Me.Recargar
  End Sub

  'Entidad
  Public Overridable Property Entidad() As Entidad
    Get
      If mEntidad Is Nothing Then
        If Entida_Codigo > 0 Then
          mEntidad = New Entidad(OperadorDatos, Me.Entida_Codigo)
        Else
          mEntidad = New Entidad(OperadorDatos, True)
        End If
      End If
      mEntidad.Entidadnatural = Me
      Return mEntidad
    End Get
    Set(ByVal value As Entidad)
      mEntidad = value
      Me.Entida_Codigo = value.Entida_Codigo
    End Set
  End Property

  'Parametrodet
  Public Overridable Property PardetSexo() As WWTSParametroDet
    Get
      If Me.mPardetSexo Is Nothing AndAlso Pardet_Sexo > 0 Then
        Me.mPardetSexo = New WWTSParametroDet(OperadorDatos, Parame_Sexo, Pardet_Sexo)
      End If
      Return Me.mPardetSexo
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mPardetSexo = value
      Parame_Sexo = value.Parame_Codigo
      Pardet_Sexo = value.Pardet_Secuencia
    End Set
  End Property

  Public ReadOnly Property PardetSexoString() As String
    Get
      If PardetSexo Is Nothing Then
        Return String.Empty
      Else
        Return PardetSexo.Pardet_Descripcion
      End If
    End Get
  End Property

  'Parametrodet
  Public Overridable Property PardetEstadoCivil() As WWTSParametroDet
    Get
      If Me.mPardetEstadoCivil Is Nothing AndAlso Pardet_Estadocivil > 0 Then
        Me.mPardetEstadoCivil = New WWTSParametroDet(OperadorDatos, Parame_Estadocivil, Pardet_Estadocivil)
      End If
      Return Me.mPardetEstadoCivil
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mPardetEstadoCivil = value
      Parame_Estadocivil = value.Parame_Codigo
      Pardet_Estadocivil = value.Pardet_Secuencia
    End Set
  End Property

  Public ReadOnly Property PardetEstadoCivilString() As String
    Get
      If PardetEstadoCivil Is Nothing Then
        Return String.Empty
      Else
        Return PardetEstadoCivil.Pardet_Descripcion
      End If
    End Get
  End Property

  Public ReadOnly Property NombreAbsoluto() As String
    Get
      Dim nombre As String = String.Empty
      nombre = String.Format("{0} {1} {2}", Entnat_Apellidopaterno, Entnat_Apellidomaterno, Entnat_Nombres)
      Return nombre
    End Get
  End Property

  Public ReadOnly Property NombreCompleto() As String
    Get
      Return String.Format("{0} {1}", Entnat_Sobrenombre, NombreAbsoluto)
    End Get
  End Property

  Public ReadOnly Property Edad() As Integer
    Get
      If Entnat_Fechanacimiento = Nothing Then
        Return 0
      Else
        Return Now.Date.Subtract(Entnat_Fechanacimiento).TotalDays / 365
      End If
    End Get
  End Property

  Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Entida_Codigo = CType(Fila("Entida_Codigo"), Integer)
    Entnat_Nombres = CType(Fila("Entnat_Nombres"), String)
    Entnat_Apellidopaterno = CType(Fila("Entnat_Apellidopaterno"), String)
    Entnat_Apellidomaterno = CType(Fila("Entnat_Apellidomaterno"), String)
    Entnat_Sobrenombre = CStr(Fila("Entnat_Sobrenombre"))
    Parame_Sexo = CType(Fila("Parame_Sexo"), Integer)
    Pardet_Sexo = CType(Fila("Pardet_Sexo"), Integer)
    Parame_Estadocivil = CType(Fila("Parame_Estadocivil"), Integer)
    Pardet_Estadocivil = CType(Fila("Pardet_Estadocivil"), Integer)
    Dim obj As Object
    obj = Fila("Entnat_Fechanacimiento")
    If TypeOf obj Is DBNull Then
      Entnat_Fechanacimiento = Nothing
    Else
      Entnat_Fechanacimiento = CType(obj, Date)
    End If
    mPardetEstadoCivil = Nothing
    mPardetSexo = Nothing
  End Sub

  Public Overridable Function Recargar() As Boolean
    Dim Result As System.Data.datatable = New System.Data.datatable
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "C")
    OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    Try
      Me.MapearDataRowaObjeto(Result.Rows(0))
      EsNuevo = False
      EsModificado = False
    Catch ex As System.Exception
      bReturn = False
    End Try
    Return bReturn
  End Function

  Public Overridable Function Guardar() As Boolean
    If Not EsNuevo And Not EsModificado Then
      Return True
    End If
    Dim Result As Integer = 0
    Dim bReturn As Boolean = True

    bReturn = Entidad.Guardar()
    If bReturn Then
      Entida_Codigo = mEntidad.Entida_Codigo

      Dim sAccion As String = "M"
      If EsNuevo Then
        sAccion = "I"
      End If
      OperadorDatos.AgregarParametro("@accion", sAccion)
      OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
      OperadorDatos.AgregarParametro("@Entnat_Nombres", Entnat_Nombres)
      OperadorDatos.AgregarParametro("@Entnat_Apellidopaterno", Entnat_Apellidopaterno)
      OperadorDatos.AgregarParametro("@Entnat_Apellidomaterno", Entnat_Apellidomaterno)
      OperadorDatos.AgregarParametro("@Entnat_Sobrenombre", Entnat_Sobrenombre)
      OperadorDatos.AgregarParametro("@Parame_Sexo", Parame_Sexo)
      OperadorDatos.AgregarParametro("@Pardet_Sexo", Pardet_Sexo)
      OperadorDatos.AgregarParametro("@Parame_Estadocivil", Parame_Estadocivil)
      OperadorDatos.AgregarParametro("@Pardet_Estadocivil", Pardet_Estadocivil)
      If Not Entnat_Fechanacimiento = Nothing Then
        OperadorDatos.AgregarParametro("@Entnat_Fechanacimiento", Entnat_Fechanacimiento)
      End If
      OperadorDatos.Procedimiento = _Procedimiento
      bReturn = OperadorDatos.Ejecutar(Result)
      OperadorDatos.LimpiarParametros()
      If bReturn Then
        If Not OperadorDatos.EstaenTransaccion Then
          EsNuevo = False
          EsModificado = False
        End If
      End If
    End If
    Return bReturn
  End Function

  Public Overridable Sub AceptarCambios(Optional ByVal _AceptarEntidad As Boolean = True)
    EsNuevo = False
    EsModificado = False
    If _AceptarEntidad Then
      mEntidad.AceptarCambios()
    End If
  End Sub

  Public Overridable Function Eliminar() As Boolean
    If EsNuevo Then
      Return True
    End If
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "E")
    OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar
    OperadorDatos.LimpiarParametros()
    Return bReturn
  End Function
End Class
#End Region

#Region "EntidadNaturalList"
Public Class EntidadNaturalList
  Inherits System.ComponentModel.BindingList(Of EntidadNatural)

  Public Shared Function ObtenerLista(ByVal _op As OperadorDatos) As EntidadNaturalList
    Dim oResult As EntidadNaturalList = New EntidadNaturalList
    Dim bReturn As Boolean
    Dim ds As datatable = Nothing
    With _op
      .AgregarParametro("@Accion", "F")
      .Procedimiento = "proc_EntidadNatural"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New EntidadNatural(_op, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function
End Class
#End Region
