'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos
Imports Infoware.Reglas.General


#Region "EntidadJuridica"
Public Class EntidadJuridica

  Const _Procedimiento As String = "proc_EntidadJuridica"

  Private mEntidad As Entidad = Nothing

  Private mEntidadRepresLegal As EntidadNatural = Nothing

  Private mEntidadContacto As EntidadNatural = Nothing

  Private mParametrodet As WWTSParametroDet = Nothing

  Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _EsNuevo As Boolean)
    MyBase.New()
    OperadorDatos = _OperadorDatos

    EsNuevo = _EsNuevo
  End Sub

  Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _Entida_Codigo As Integer)
    Me.New(_OperadorDatos, False)
    Entida_Codigo = _Entida_Codigo
    EsNuevo = Not Me.Recargar
  End Sub

  'Entidad
  Public Overridable Property Entidad() As Entidad
    Get
      If mEntidad Is Nothing Then
        If Entida_Codigo > 0 Then
          mEntidad = New Entidad(OperadorDatos, Me.Entida_Codigo)
        Else
          mEntidad = New Entidad(OperadorDatos, Enumerados.EnumTipoEntidad.Juridica, True)
        End If
      End If
      mEntidad.Entidadjuridica = Me
      Return mEntidad
    End Get
    Set(ByVal value As Entidad)
      mEntidad = value
      Me.Entida_Codigo = value.Entida_Codigo
    End Set
  End Property

  'Entidadnatural
  Public Overridable Property RepresentanteLegal() As EntidadNatural
    Get
      If Me.mEntidadRepresLegal Is Nothing AndAlso Entida_RepresLegal > 0 Then
        Me.mEntidadRepresLegal = New EntidadNatural(OperadorDatos, Entida_RepresLegal)
      End If
      Return Me.mEntidadRepresLegal
    End Get
    Set(ByVal value As EntidadNatural)
      Me.mEntidadRepresLegal = value
      If value Is Nothing Then
        Entida_RepresLegal = 0
      Else
        Entida_RepresLegal = value.Entida_Codigo
      End If
    End Set
  End Property

  Public ReadOnly Property RepresentanteLegalString() As String
    Get
      If RepresentanteLegal Is Nothing Then
        Return String.Empty
      Else
        Return RepresentanteLegal.NombreCompleto
      End If
    End Get
  End Property

  'Entidadnatural
  Public Overridable Property Contacto() As EntidadNatural
    Get
      If Me.mEntidadContacto Is Nothing AndAlso Entida_Contacto > 0 Then
        Me.mEntidadContacto = New EntidadNatural(OperadorDatos, Entida_Contacto)
      End If
      Return Me.mEntidadContacto
    End Get
    Set(ByVal value As EntidadNatural)
      Me.mEntidadContacto = value
      If value Is Nothing Then
        Entida_Contacto = 0
      Else
        Entida_Contacto = value.Entida_Codigo
      End If
    End Set
  End Property

  Public ReadOnly Property ContactoString() As String
    Get
      If Contacto Is Nothing Then
        Return String.Empty
      Else
        Return Contacto.NombreCompleto
      End If
    End Get
  End Property

  'Parametrodet
  Public Overridable Property PardetTipoContribuyente() As WWTSParametroDet
    Get
      If Me.mParametrodet Is Nothing AndAlso Pardet_Tipocontribuyente > 0 Then
        Me.mParametrodet = New WWTSParametroDet(OperadorDatos, Parame_Tipocontribuyente, Pardet_Tipocontribuyente)
      End If
      Return Me.mParametrodet
    End Get
    Set(ByVal value As WWTSParametroDet)
      Me.mParametrodet = value
      Parame_Tipocontribuyente = value.Parame_Codigo
      Pardet_Tipocontribuyente = value.Pardet_Secuencia
    End Set
  End Property

  Public ReadOnly Property NombreAbsoluto() As String
    Get
      Dim nombre As String = String.Empty
      If Not Entjur_Razonsocial.Trim = String.Empty Then
        nombre = String.Format("{0}", Entjur_Razonsocial)
      Else 'If Not Entjur_Nombrecomercial.Trim = String.Empty Then
        nombre = String.Format("{0}", Entjur_Nombrecomercial)
        'Else
        'nombre = String.Format("{0}  {1}", Entjur_Nombrecomercial, Entjur_Razonsocial).Trim
      End If
      Return nombre
    End Get
  End Property

  Public ReadOnly Property NombreCompleto() As String
    Get
      Return String.Format("{0} {1}", Entjur_Razonsocial, Entjur_Nombrecomercial)
    End Get
  End Property

  Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Dim obj As Object
    Entida_Codigo = CType(Fila("Entida_Codigo"), Integer)
    Entjur_Nombrecomercial = CType(Fila("Entjur_Nombrecomercial"), String)
    Entjur_Razonsocial = CType(Fila("Entjur_Razonsocial"), String)
    obj = Fila("Entjur_Fechaconstitucion")
    If TypeOf obj Is DBNull Then
      Entjur_Fechaconstitucion = Nothing
    Else
      Entjur_Fechaconstitucion = CType(obj, Date)
    End If
    Parame_Tipocontribuyente = CType(Fila("Parame_Tipocontribuyente"), Integer)
    Pardet_Tipocontribuyente = CType(Fila("Pardet_Tipocontribuyente"), Integer)
    obj = Fila("Entida_RepresLegal")
    If TypeOf obj Is DBNull Then
      Entida_RepresLegal = 0
    Else
      Entida_RepresLegal = CType(obj, Integer)
    End If
    mEntidadRepresLegal = Nothing
    mParametrodet = Nothing
  End Sub

  Public Overridable Function Recargar() As Boolean
    Dim Result As System.Data.datatable = New System.Data.datatable
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "C")
    OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    Try
      Me.MapearDataRowaObjeto(Result.Rows(0))
      EsNuevo = False
      EsModificado = False
    Catch ex As System.Exception
      bReturn = False
    End Try
    Return bReturn
  End Function

  Public Overridable Function Guardar() As Boolean
    If Not EsNuevo And Not EsModificado Then
      Return True
    End If
    Dim Result As Integer = 0
    Dim bReturn As Boolean = True

    bReturn = Entidad.Guardar()
    If bReturn Then
      Entida_Codigo = mEntidad.Entida_Codigo

      Dim sAccion As String = "M"
      If EsNuevo Then
        sAccion = "I"
      End If
      OperadorDatos.AgregarParametro("@accion", sAccion)
      OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
      OperadorDatos.AgregarParametro("@Entjur_Nombrecomercial", Entjur_Nombrecomercial)
      OperadorDatos.AgregarParametro("@Entjur_Razonsocial", Entjur_Razonsocial)
      If Not Entjur_Fechaconstitucion = Nothing Then
        OperadorDatos.AgregarParametro("@Entjur_Fechaconstitucion", Entjur_Fechaconstitucion)
      End If
      OperadorDatos.AgregarParametro("@Parame_Tipocontribuyente", Parame_Tipocontribuyente)
      OperadorDatos.AgregarParametro("@Pardet_Tipocontribuyente", Pardet_Tipocontribuyente)
      If Entida_RepresLegal > 0 Then
        OperadorDatos.AgregarParametro("@Entida_RepresLegal", Entida_RepresLegal)
      End If
      OperadorDatos.Procedimiento = _Procedimiento
      bReturn = OperadorDatos.Ejecutar(Result)
      OperadorDatos.LimpiarParametros()
      If bReturn Then
        If Not OperadorDatos.EstaenTransaccion Then
          EsNuevo = False
          EsModificado = False
        End If
      End If
    End If
    Return bReturn
  End Function

  Public Overridable Sub AceptarCambios(Optional ByVal _AceptarEntidad As Boolean = True)
    EsNuevo = False
    EsModificado = False
    If _AceptarEntidad Then
      mEntidad.AceptarCambios()
    End If
  End Sub

  Public Overridable Function Eliminar() As Boolean
    If EsNuevo Then
      Return True
    End If
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "E")
    OperadorDatos.AgregarParametro("@Entida_Codigo", Entida_Codigo)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar
    OperadorDatos.LimpiarParametros()
    Return bReturn
  End Function
End Class
#End Region

#Region "EntidadJuridicaList"
Public Class EntidadJuridicaList
  Inherits System.ComponentModel.BindingList(Of EntidadJuridica)

  Public Shared Function ObtenerLista(ByVal _op As OperadorDatos) As EntidadJuridicaList
    Dim oResult As EntidadJuridicaList = New EntidadJuridicaList
    Dim bReturn As Boolean
    Dim ds As datatable = Nothing
    With _op
      .AgregarParametro("@Accion", "F")
      .Procedimiento = "proc_EntidadJuridica"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New EntidadJuridica(_op, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function
End Class
#End Region
