'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos
Imports Infoware.Reglas.General



#Region "ItemPrecioxCantidad"
Public Class ItemPrecioxCantidad

  Const _Procedimiento As String = "proc_ItemPrecioxCantidad"

  Private mItem As Item = Nothing

  Private mSucursal As Sucursal = Nothing

  Public Sub New(ByVal _Item As Item, ByVal _EsNuevo As Boolean)
    MyBase.New()
    Item = _Item
    OperadorDatos = _Item.OperadorDatos
    EsNuevo = _EsNuevo
  End Sub

  Public Sub New(ByVal _Item As Item, ByVal _Sucursal As Sucursal)
    Me.New(_Item, False)
    Sucursal = _Sucursal
    If Me.Recargar Then
    Else
      Throw New System.Exception("No se puede cargar objeto ItemPrecioxCantidad")
    End If
  End Sub

  'Item
  Public Overridable Property Item() As Item
    Get
      If Me.mItem Is Nothing AndAlso Item_Codigo > 0 Then
        Me.mItem = New Item(OperadorDatos, Item_Codigo)
      End If
      Return Me.mItem
    End Get
    Set(ByVal value As Item)
      Me.mItem = value
      Item_Codigo = value.Item_Codigo
    End Set
  End Property

  'Sucursal
  Public Overridable Overloads Property Sucursal() As Sucursal
    Get
      If Me.mSucursal Is Nothing AndAlso Sucurs_Codigo > 0 Then
        Me.mSucursal = New Sucursal(New Empresa(OperadorDatos, Me.Empres_Codigo), Me.Sucurs_Codigo)
      End If
      Return Me.mSucursal
    End Get
    Set(ByVal value As Sucursal)
      Me.mSucursal = value
      Empres_Codigo = value.Empres_Codigo
      Sucurs_Codigo = value.Sucurs_Codigo
    End Set
  End Property

  Public Overridable ReadOnly Property SucursalString() As String
    Get
      If Sucursal Is Nothing Then
        Return String.Empty
      Else
        Return mSucursal.NombreCompleto
      End If
    End Get
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Cantidad desde", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Decimales, 65, True)> _
  Public Property Cantidad() As Decimal
    Get
      Return ItPrCa_CantidadDesde
    End Get
    Set(ByVal value As Decimal)
      ItPrCa_CantidadDesde = value
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Valor unitario", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Decimales, 65, True)> _
  Public Property Valor() As Decimal
    Get
      Return ItPrCa_ValorUnitario
    End Get
    Set(ByVal value As Decimal)
      ItPrCa_ValorUnitario = value
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Total", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Decimales, 70, True)> _
  Public ReadOnly Property Total() As Decimal
    Get
      Return ItPrCa_CantidadDesde * ItPrCa_ValorUnitario
    End Get
  End Property

  Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Empres_Codigo = CType(Fila("Empres_Codigo"), Integer)
    Sucurs_Codigo = CType(Fila("Sucurs_Codigo"), Integer)
    Item_Codigo = CType(Fila("Item_Codigo"), Integer)
    ItPrCa_Secuencia = CInt(Fila("ItPrCa_Secuencia"))
    ItPrCa_CantidadDesde = CDec(Fila("ItPrCa_CantidadDesde"))
    ItPrCa_ValorUnitario = CDec(Fila("ItPrCa_ValorUnitario"))
    mItem = Nothing
    mSucursal = Nothing
  End Sub

  Public Overridable Function Recargar() As Boolean
    Dim Result As New DataTable
    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "C")
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Item_Codigo", Item_Codigo)
    OperadorDatos.AgregarParametro("@ItPrCa_Secuencia", ItPrCa_Secuencia)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    Try
      Me.MapearDataRowaObjeto(Result.Rows(0))
      EsNuevo = False
      EsModificado = False
    Catch ex As System.Exception
      bReturn = False
    End Try
    Return bReturn
  End Function

  Public Overridable Function Guardar() As Boolean
    If Not EsNuevo And Not EsModificado Then
      Return True
    End If

    Dim Result As Integer = 0
    Dim bReturn As Boolean = True
    Dim sAccion As String = "M"
    If EsNuevo Then
      sAccion = "I"
    End If
    OperadorDatos.AgregarParametro("@accion", sAccion)
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Item_Codigo", Item_Codigo)
    OperadorDatos.AgregarParametro("@ItPrCa_Secuencia", ItPrCa_Secuencia)
    OperadorDatos.AgregarParametro("@ItPrCa_CantidadDesde", ItPrCa_CantidadDesde)
    OperadorDatos.AgregarParametro("@ItPrCa_ValorUnitario", ItPrCa_ValorUnitario)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    If bReturn Then
      If EsNuevo Then
        ItPrCa_Secuencia = Result
      End If

      If Not OperadorDatos.EstaenTransaccion Then
        AceptarCambios()
      End If
    End If
    Return bReturn
  End Function

  Public Overridable Sub AceptarCambios()
    EsNuevo = False
    EsModificado = False
  End Sub

  Public Overridable Function Eliminar() As Boolean
    If EsNuevo Then
      Return True
    End If

    Dim bReturn As Boolean = True
    OperadorDatos.AgregarParametro("@accion", "E")
    OperadorDatos.AgregarParametro("@Empres_Codigo", Empres_Codigo)
    OperadorDatos.AgregarParametro("@Sucurs_Codigo", Sucurs_Codigo)
    OperadorDatos.AgregarParametro("@Item_Codigo", Item_Codigo)
    OperadorDatos.AgregarParametro("@ItPrCa_Secuencia", ItPrCa_Secuencia)
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar
    OperadorDatos.LimpiarParametros()
    Return bReturn
  End Function
End Class
#End Region

#Region "ItemPrecioxCantidadList"
Public Class ItemPrecioxCantidadList
  Inherits System.ComponentModel.BindingList(Of ItemPrecioxCantidad)

  Public Shared Function ObtenerLista(ByVal _Item As Item, ByVal _Sucursal As Sucursal) As ItemPrecioxCantidadList
    Dim oResult As ItemPrecioxCantidadList = New ItemPrecioxCantidadList
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _Item.OperadorDatos
      .AgregarParametro("@Accion", "F")
      .AgregarParametro("@Empres_Codigo", _Sucursal.Empres_Codigo)
      .AgregarParametro("@Sucurs_Codigo", _Sucursal.Sucurs_Codigo)
      .AgregarParametro("@Item_Codigo", _Item.Item_Codigo)
      .Procedimiento = "proc_ItemPrecioxCantidad"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New ItemPrecioxCantidad(_Item, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function

  Public Shared Function ObtenerPrecioxCantidad(ByVal _Item As Item, ByVal _Sucursal As Sucursal, ByVal _Cantidad As Decimal) As ItemPrecioxCantidad
    Dim oResult As ItemPrecioxCantidad = Nothing
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _Item.OperadorDatos
      .AgregarParametro("@Accion", "FC")
      .AgregarParametro("@Empres_Codigo", _Sucursal.Empres_Codigo)
      .AgregarParametro("@Sucurs_Codigo", _Sucursal.Sucurs_Codigo)
      .AgregarParametro("@Item_Codigo", _Item.Item_Codigo)
      .AgregarParametro("@ItPrCa_CantidadDesde", _Cantidad)
      .Procedimiento = "proc_ItemPrecioxCantidad"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      Dim _fila As New ItemPrecioxCantidad(_Item, False)
      _fila.MapearDataRowaObjeto(ds.Rows(0))
      oResult = _fila
    End If
    Return oResult
  End Function
End Class
#End Region
