'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Cliente"
Partial Public Class Cliente
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mClient_Visible As Boolean = True

  Private mEntida_Vendedor As Integer = 0

  Private mParame_TipoPrecio As Integer = 0

  Private mPardet_TipoPrecio As Integer = 0

  Private mClient_CupoCreditoMaximo As Decimal = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Activo", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Logico, 50, True)> _
  <XmlAttribute()> _
  Public Overridable Property Client_Visible() As Boolean
    Get
      Return Me.mClient_Visible
    End Get
    Set(ByVal value As Boolean)
      Me.mClient_Visible = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_Vendedor() As Integer
    Get
      Return Me.mEntida_Vendedor
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Vendedor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoPrecio() As Integer
    Get
      Return Me.mParame_TipoPrecio
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoPrecio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoPrecio() As Integer
    Get
      Return Me.mPardet_TipoPrecio
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoPrecio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Client_CupoCreditoMaximo() As Decimal
    Get
      Return Me.mClient_CupoCreditoMaximo
    End Get
    Set(ByVal value As Decimal)
      Me.mClient_CupoCreditoMaximo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

