'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas
Imports Infoware.Reglas.General

#Region "Compra"
Partial Public Class Compra
  Inherits _Database

  Private mEmpres_Codigo As Integer = 0

  Private mSucurs_Codigo As Integer = 0

  Private mParame_TipoCompra As Integer = 441

  Private mPardet_TipoCompra As Integer = 1

  Private mEntida_Proveedor As Integer = 0

  Private mCompra_Numero As String = String.Empty

  Private mParame_Tipomovinv As Integer = 440

  Private mPardet_TipoMovinv As Integer = 1

  Private mMovinv_Secuencia As Integer = 0

  Private mParame_TipoPago As Integer = CInt(Enumerados.EnumParametros.TipoFormaPago)

  Private mPardet_TipoPago As Integer = CInt(Enumerados.enumTipoFormaPago.Contado)

  Private mSRI_secuencialtransaccion As String = String.Empty

  Private mSRI_tipocomprobante As String = String.Empty

  Private mSRI_creditotributario As String = String.Empty

  Private mCompra_Autorizacion As String = String.Empty

  Private mCompra_Caducidad As String = String.Empty

  Private mParame_Tipodireccion As Integer = 0

  Private mPardet_Tipodireccion As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return Me.mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Codigo() As Integer
    Get
      Return Me.mSucurs_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoCompra() As Integer
    Get
      Return Me.mParame_TipoCompra
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoCompra = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoCompra() As Integer
    Get
      Return Me.mPardet_TipoCompra
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoCompra = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_Proveedor() As Integer
    Get
      Return Me.mEntida_Proveedor
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Proveedor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Compra_Numero() As String
    Get
      Return Me.mCompra_Numero
    End Get
    Set(ByVal value As String)
      Me.mCompra_Numero = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipomovinv() As Integer
    Get
      Return Me.mParame_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoMovinv() As Integer
    Get
      Return Me.mPardet_TipoMovinv
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoMovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Secuencia() As Integer
    Get
      Return Me.mMovinv_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mMovinv_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoPago() As Integer
    Get
      Return Me.mParame_TipoPago
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoPago = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoPago() As Integer
    Get
      Return Me.mPardet_TipoPago
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoPago = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property SRI_secuencialtransaccion() As String
    Get
      Return Me.mSRI_secuencialtransaccion
    End Get
    Set(ByVal value As String)
      Me.mSRI_secuencialtransaccion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property SRI_tipocomprobante() As String
    Get
      Return Me.mSRI_tipocomprobante
    End Get
    Set(ByVal value As String)
      Me.mSRI_tipocomprobante = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property SRI_creditotributario() As String
    Get
      Return Me.mSRI_creditotributario
    End Get
    Set(ByVal value As String)
      Me.mSRI_creditotributario = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Compra_Autorizacion() As String
    Get
      Return Me.mCompra_Autorizacion
    End Get
    Set(ByVal value As String)
      Me.mCompra_Autorizacion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Compra_Caducidad() As String
    Get
      Return Me.mCompra_Caducidad
    End Get
    Set(ByVal value As String)
      Me.mCompra_Caducidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipodireccion() As Integer
    Get
      Return mParame_Tipodireccion
    End Get
    Set(ByVal value As Integer)
      mParame_Tipodireccion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipodireccion() As Integer
    Get
      Return mPardet_Tipodireccion
    End Get
    Set(ByVal value As Integer)
      mPardet_Tipodireccion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
