'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "CuentaBancaria"
Partial Public Class CuentaBancaria
  Inherits _Database

  Private mEmpres_Codigo As Integer = 0

  Private mParame_Banco As Integer = CInt(Enumerados.EnumParametros.Banco)

  Private mPardet_Banco As Integer = 0

  Private mCtaBan_Numero As String = ""

  Private mParame_TipoCuentaBancaria As Integer = CInt(Enumerados.EnumParametros.TipoCtaBan)

  Private mPardet_TipoCuentaBancaria As Integer = 0

  Private mCtaBan_UltimoCheque As Integer = 0

  Private mCtaCtb_Codigo As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return Me.mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Banco() As Integer
    Get
      Return Me.mParame_Banco
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Banco = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Banco() As Integer
    Get
      Return Me.mPardet_Banco
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Banco = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Número de cuenta", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 130, True)> _
  <XmlAttribute()> _
  Public Overridable Property CtaBan_Numero() As String
    Get
      Return Me.mCtaBan_Numero
    End Get
    Set(ByVal value As String)
      Me.mCtaBan_Numero = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoCuentaBancaria() As Integer
    Get
      Return Me.mParame_TipoCuentaBancaria
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoCuentaBancaria() As Integer
    Get
      Return Me.mPardet_TipoCuentaBancaria
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Ultimo cheque girado", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Numero, 100, True)> _
  <XmlAttribute()> _
  Public Overridable Property CtaBan_UltimoCheque() As Integer
    Get
      Return Me.mCtaBan_UltimoCheque
    End Get
    Set(ByVal value As Integer)
      Me.mCtaBan_UltimoCheque = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property CtaCtb_Codigo() As String
    Get
      Return Me.mCtaCtb_Codigo
    End Get
    Set(ByVal value As String)
      Me.mCtaCtb_Codigo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

