'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Empleado"
Partial Public Class Empleado
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mParame_Tipoempleado As Integer = 0

  Private mPardet_Tipoempleado As Integer = 0

  Private mEmplea_Visible As Boolean = True

  Private mParame_ClaseEmpleado As Integer = 705

  Private mPardet_ClaseEmpleado As Integer = 1

  Private mParame_Parroquia As Integer = 230

  Private mPardet_Parroquia As Integer = 1

  Private mParame_Banco As Integer = 0

  Private mPardet_Banco As Integer = 0

  Private mParame_TipoSangre As Integer = 0

  Private mPardet_TipoSangre As Integer = 0

  Private mParame_Nacionalidad As Integer = 0

  Private mPardet_Nacionalidad As Integer = 0

  Private mEmplea_Emergencia As String = ""

  Private mEmplea_Enfermedad As String = ""

  Private mEmplea_FichaRoja As Boolean = 0

  Private mParame_TipoCuentaBancaria As Integer = 0

  Private mPardet_TipoCuentaBancaria As Integer = 0

  Private mEmplea_NumeroCuentaBancaria As String = ""

  Private mParame_FormaPagoRol As Integer = 720

  Private mPardet_FormaPagoRol As Integer = 1

  Private mEmplea_JubilacionPatronal As Decimal = 0

  Private mEmplea_DesctoPrestQuirogMensual As Decimal = 0

  Private mEmplea_Primaria As String = ""

  Private mEmplea_Primariaanio As String = ""

  Private mEmplea_Secundaria As String = ""

  Private mEmplea_Secundariaanio As String = ""

  Private mEmplea_Bachiller As String = ""

  Private mEmplea_Superior As String = ""

  Private mEmplea_Superioranio As String = ""

  Private mEmplea_Titulo As String = ""

  Private mEmplea_Cursos As String = ""

  Private mEmplea_ReferPersonales As String = ""

  Private mEmplea_ReferLaborales As String = ""

  Private mEmplea_ExcluirFamiliares As Boolean = False

  Private mEmplea_FechaAfiliacionIESS As DateTime = Now.Date

  Private mParame_TipoDiscapacidad As Integer = 707

  Private mPardet_TipoDiscapacidad As Integer = 1

  Private mEmplea_DiscaFisica As Boolean = False

  Private mEmplea_DiscaAuditiva As Boolean = False

  Private mEmplea_DiscaLenguaje As Boolean = False

  Private mEmplea_DiscaVisual As Boolean = False

  Private mEmplea_DiscaIntelectual As Boolean = False

  Private mEmplea_DiscaPsicologica As Boolean = False

  Private mParame_SeguroCorporativo As Integer = 724

  Private mPardet_SeguroCorporativo As Integer = 1

  Private mParame_SectorDomicilio As Integer = 0

  Private mPardet_SectorDomicilio As Integer = 0

  Private mParame_AdjuntoArchivos As Integer = 0

  Private mPardet_AdjuntoArchivos As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipoempleado() As Integer
    Get
      Return Me.mParame_Tipoempleado
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipoempleado = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipoempleado() As Integer
    Get
      Return Me.mPardet_Tipoempleado
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipoempleado = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Visible() As Boolean
    Get
      Return Me.mEmplea_Visible
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_Visible = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_ClaseEmpleado() As Integer
    Get
      Return Me.mParame_ClaseEmpleado
    End Get
    Set(ByVal value As Integer)
      Me.mParame_ClaseEmpleado = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_ClaseEmpleado() As Integer
    Get
      Return Me.mPardet_ClaseEmpleado
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_ClaseEmpleado = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Parroquia() As Integer
    Get
      Return Me.mParame_Parroquia
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Parroquia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Parroquia() As Integer
    Get
      Return Me.mPardet_Parroquia
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Parroquia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Banco() As Integer
    Get
      Return Me.mParame_Banco
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Banco = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Banco() As Integer
    Get
      Return Me.mPardet_Banco
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Banco = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoSangre() As Integer
    Get
      Return Me.mParame_TipoSangre
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoSangre = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoSangre() As Integer
    Get
      Return Me.mPardet_TipoSangre
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoSangre = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Nacionalidad() As Integer
    Get
      Return Me.mParame_Nacionalidad
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Nacionalidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Nacionalidad() As Integer
    Get
      Return Me.mPardet_Nacionalidad
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Nacionalidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Emergencia() As String
    Get
      Return Me.mEmplea_Emergencia
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Emergencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Enfermedad() As String
    Get
      Return Me.mEmplea_Enfermedad
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Enfermedad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_FichaRoja() As Boolean
    Get
      Return Me.mEmplea_FichaRoja
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_FichaRoja = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoCuentaBancaria() As Integer
    Get
      Return Me.mParame_TipoCuentaBancaria
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoCuentaBancaria() As Integer
    Get
      Return Me.mPardet_TipoCuentaBancaria
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_NumeroCuentaBancaria() As String
    Get
      Return Me.mEmplea_NumeroCuentaBancaria
    End Get
    Set(ByVal value As String)
      Me.mEmplea_NumeroCuentaBancaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_FormaPagoRol() As Integer
    Get
      Return Me.mParame_FormaPagoRol
    End Get
    Set(ByVal value As Integer)
      Me.mParame_FormaPagoRol = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_FormaPagoRol() As Integer
    Get
      Return Me.mPardet_FormaPagoRol
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_FormaPagoRol = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_JubilacionPatronal() As Decimal
    Get
      Return Me.mEmplea_JubilacionPatronal
    End Get
    Set(ByVal value As Decimal)
      Me.mEmplea_JubilacionPatronal = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_DesctoPrestQuirogMensual() As Decimal
    Get
      Return Me.mEmplea_DesctoPrestQuirogMensual
    End Get
    Set(ByVal value As Decimal)
      Me.mEmplea_DesctoPrestQuirogMensual = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Primaria() As String
    Get
      Return Me.mEmplea_Primaria
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Primaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Primariaanio() As String
    Get
      Return Me.mEmplea_Primariaanio
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Primariaanio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Secundaria() As String
    Get
      Return Me.mEmplea_Secundaria
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Secundaria = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Secundariaanio() As String
    Get
      Return Me.mEmplea_Secundariaanio
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Secundariaanio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Bachiller() As String
    Get
      Return Me.mEmplea_Bachiller
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Bachiller = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Superior() As String
    Get
      Return Me.mEmplea_Superior
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Superior = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Superioranio() As String
    Get
      Return Me.mEmplea_Superioranio
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Superioranio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Titulo() As String
    Get
      Return Me.mEmplea_Titulo
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Titulo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Cursos() As String
    Get
      Return Me.mEmplea_Cursos
    End Get
    Set(ByVal value As String)
      Me.mEmplea_Cursos = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_ReferPersonales() As String
    Get
      Return Me.mEmplea_ReferPersonales
    End Get
    Set(ByVal value As String)
      Me.mEmplea_ReferPersonales = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_ReferLaborales() As String
    Get
      Return Me.mEmplea_ReferLaborales
    End Get
    Set(ByVal value As String)
      Me.mEmplea_ReferLaborales = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_ExcluirFamiliares() As Boolean
    Get
      Return Me.mEmplea_ExcluirFamiliares
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_ExcluirFamiliares = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_FechaAfiliacionIESS() As DateTime
    Get
      Return Me.mEmplea_FechaAfiliacionIESS
    End Get
    Set(ByVal value As DateTime)
      Me.mEmplea_FechaAfiliacionIESS = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
 Public Overridable Property Parame_TipoDiscapacidad() As Integer
    Get
      Return Me.mParame_TipoDiscapacidad
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoDiscapacidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoDiscapacidad() As Integer
    Get
      Return Me.mPardet_TipoDiscapacidad
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoDiscapacidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_DiscaFisica() As Boolean
    Get
      Return Me.mEmplea_DiscaFisica
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaFisica = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_DiscaAuditiva() As Boolean
    Get
      Return Me.mEmplea_DiscaAuditiva
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaAuditiva = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_DiscaLenguaje() As Boolean
    Get
      Return Me.mEmplea_DiscaLenguaje
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaLenguaje = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_DiscaVisual() As Boolean
    Get
      Return Me.mEmplea_DiscaVisual
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaVisual = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
Public Overridable Property Emplea_DiscaIntelectual() As Boolean
    Get
      Return Me.mEmplea_DiscaIntelectual
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaIntelectual = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
Public Overridable Property Emplea_DiscaPsicologica() As Boolean
    Get
      Return Me.mEmplea_DiscaPsicologica
    End Get
    Set(ByVal value As Boolean)
      Me.mEmplea_DiscaPsicologica = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_SeguroCorporativo() As Integer
    Get
      Return Me.mParame_SeguroCorporativo
    End Get
    Set(ByVal value As Integer)
      Me.mParame_SeguroCorporativo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_SeguroCorporativo() As Integer
    Get
      Return Me.mPardet_SeguroCorporativo
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_SeguroCorporativo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_SectorDomicilio() As Integer
    Get
      Return Me.mParame_SectorDomicilio
    End Get
    Set(ByVal value As Integer)
      Me.mParame_SectorDomicilio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_SectorDomicilio() As Integer
    Get
      Return Me.mPardet_SectorDomicilio
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_SectorDomicilio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_AdjuntoArchivos() As Integer
    Get
      Return Me.mParame_AdjuntoArchivos
    End Get
    Set(ByVal value As Integer)
      Me.mParame_AdjuntoArchivos = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_AdjuntoArchivos() As Integer
    Get
      Return Me.mPardet_AdjuntoArchivos
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_AdjuntoArchivos = value
      EsModificado = True
    End Set
  End Property

End Class
#End Region
