'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "EntidadDireccion"
Partial Public Class EntidadDireccion
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mParame_Tipodireccion As Integer = CInt(Enumerados.EnumParametros.TipoDireccion)

  Private mPardet_Tipodireccion As Integer = 0

  Private mParame_Ciudad As Integer = CInt(Enumerados.EnumParametros.Ciudad)

  Private mPardet_Ciudad As Integer = 0

  Private mDirecc_Calleprincipal As String = ""

  Private mDirecc_Numero As String = ""

  Private mDirecc_Calleinterseccion As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipodireccion() As Integer
    Get
      Return Me.mParame_Tipodireccion
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipodireccion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipodireccion() As Integer
    Get
      Return Me.mPardet_Tipodireccion
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipodireccion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Ciudad() As Integer
    Get
      Return Me.mParame_Ciudad
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Ciudad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Ciudad() As Integer
    Get
      Return Me.mPardet_Ciudad
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Ciudad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Direcc_Calleprincipal() As String
    Get
      Return Me.mDirecc_Calleprincipal
    End Get
    Set(ByVal value As String)
      Me.mDirecc_Calleprincipal = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Direcc_Numero() As String
    Get
      Return Me.mDirecc_Numero
    End Get
    Set(ByVal value As String)
      Me.mDirecc_Numero = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Direcc_Calleinterseccion() As String
    Get
      Return Me.mDirecc_Calleinterseccion
    End Get
    Set(ByVal value As String)
      Me.mDirecc_Calleinterseccion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

