'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "EntidadIdentificacion"
Partial Public Class EntidadIdentificacion
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mParame_Tipoidentificacion As Integer = CInt(Enumerados.EnumParametros.TipoIdentificacion)

  Private mPardet_Tipoidentificacion As Integer = 0

  Private mIdenti_Numero As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipoidentificacion() As Integer
    Get
      Return Me.mParame_Tipoidentificacion
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipoidentificacion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipoidentificacion() As Integer
    Get
      Return Me.mPardet_Tipoidentificacion
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipoidentificacion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Identi_Numero() As String
    Get
      Return Me.mIdenti_Numero
    End Get
    Set(ByVal value As String)
      Me.mIdenti_Numero = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

