'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "EntidadJuridica"
Partial Public Class EntidadJuridica
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mEntjur_Nombrecomercial As String = ""

  Private mEntjur_Razonsocial As String = ""

  Private mEntjur_Fechaconstitucion As Date = Nothing

  Private mParame_Tipocontribuyente As Integer = CInt(Enumerados.EnumParametros.TipoContribuyente)

  Private mPardet_Tipocontribuyente As Integer = 0

  Private mEntida_RepresLegal As Integer = 0

  Private mEntida_Contacto As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entjur_Nombrecomercial() As String
    Get
      Return Me.mEntjur_Nombrecomercial
    End Get
    Set(ByVal value As String)
      Me.mEntjur_Nombrecomercial = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entjur_Razonsocial() As String
    Get
      Return Me.mEntjur_Razonsocial
    End Get
    Set(ByVal value As String)
      Me.mEntjur_Razonsocial = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entjur_Fechaconstitucion() As Date
    Get
      Return Me.mEntjur_Fechaconstitucion
    End Get
    Set(ByVal value As Date)
      Me.mEntjur_Fechaconstitucion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipocontribuyente() As Integer
    Get
      Return Me.mParame_Tipocontribuyente
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipocontribuyente = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipocontribuyente() As Integer
    Get
      Return Me.mPardet_Tipocontribuyente
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipocontribuyente = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_RepresLegal() As Integer
    Get
      Return Me.mEntida_RepresLegal
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_RepresLegal = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_Contacto() As Integer
    Get
      Return Me.mEntida_Contacto
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Contacto = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

