'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas
Imports Colorama.Reglas


#Region "Entidad"
Partial Public Class Entidad
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mParame_Tipoentidad As Integer = CInt(Enumerados.EnumParametros.TipoEntidad)

  Private mPardet_Tipoentidad As Integer = 0

  Private mEntida_AutorizacionFactura As String = ""

  Private mEntida_CaducidadFactura As String = ""

  Private mEntida_AutorizacionNotaVenta As String = ""

  Private mEntida_CaducidadNotaVenta As String = ""

  Private mEntida_AutorizacionRetencion As String = ""

  Private mEntida_CaducidadRetencion As String = ""

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipoentidad() As Integer
    Get
      Return Me.mParame_Tipoentidad
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipoentidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipoentidad() As Integer
    Get
      Return Me.mPardet_Tipoentidad
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipoentidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_AutorizacionFactura() As String
    Get
      Return Me.mEntida_AutorizacionFactura
    End Get
    Set(ByVal value As String)
      Me.mEntida_AutorizacionFactura = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_CaducidadFactura() As String
    Get
      Return Me.mEntida_CaducidadFactura
    End Get
    Set(ByVal value As String)
      Me.mEntida_CaducidadFactura = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_AutorizacionNotaVenta() As String
    Get
      Return Me.mEntida_AutorizacionNotaVenta
    End Get
    Set(ByVal value As String)
      Me.mEntida_AutorizacionNotaVenta = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_CaducidadNotaVenta() As String
    Get
      Return Me.mEntida_CaducidadNotaVenta
    End Get
    Set(ByVal value As String)
      Me.mEntida_CaducidadNotaVenta = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_AutorizacionRetencion() As String
    Get
      Return Me.mEntida_AutorizacionRetencion
    End Get
    Set(ByVal value As String)
      Me.mEntida_AutorizacionRetencion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_CaducidadRetencion() As String
    Get
      Return Me.mEntida_CaducidadRetencion
    End Get
    Set(ByVal value As String)
      Me.mEntida_CaducidadRetencion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

