'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas
Imports Infoware.Reglas.General


#Region "Item"
Partial Public Class Item
  Inherits _Database

  Private mItem_Codigo As Integer = 0

  Private mParame_Grupo As Integer = CInt(Enumerados.EnumParametros.Grupo)

  Private mPardet_Grupo As Integer = 0

  Private mParame_Marca As Integer = CInt(Enumerados.EnumParametros.Marca)

  Private mPardet_Marca As Integer = 0

  Private mParame_Tipoinventario As Integer = CInt(Enumerados.EnumParametros.TipoInventario)

  Private mPardet_Tipoinventario As Integer = 0

  Private mItem_Aplicaiva As Boolean = True

  Private mItem_Estangible As Boolean = True

  Private mItem_Descripcion As String = ""

  Private mItem_Ubicacion As String = ""

  Private mParame_Unidadmedida As Integer = CInt(Enumerados.EnumParametros.UnidadMedida)

  Private mPardet_Unidadmedida As Integer = 0

  Private mItem_CodigoAuxiliar As String = ""

  Private mItem_CodigoProveedor As String = ""

  Private mItem_esIvaIncluido As Boolean = False

  Private mItem_esRegistroSerie As Boolean = False

  Private mEntida_Proveedor As Integer = 0

  Private mItem_Combo As Boolean = False

  Private mItem_PrecioxCantidad As Boolean = False

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Código", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 50, True)> _
  Public Overridable Property Item_Codigo() As Integer
    Get
      Return Me.mItem_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mItem_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Grupo() As Integer
    Get
      Return Me.mParame_Grupo
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Grupo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Grupo() As Integer
    Get
      Return Me.mPardet_Grupo
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Grupo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Marca() As Integer
    Get
      Return Me.mParame_Marca
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Marca = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Marca() As Integer
    Get
      Return Me.mPardet_Marca
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Marca = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipoinventario() As Integer
    Get
      Return Me.mParame_Tipoinventario
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipoinventario = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipoinventario() As Integer
    Get
      Return Me.mPardet_Tipoinventario
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipoinventario = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Aplicaiva() As Boolean
    Get
      Return Me.mItem_Aplicaiva
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_Aplicaiva = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Estangible() As Boolean
    Get
      Return Me.mItem_Estangible
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_Estangible = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Descripción", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 150, True)> _
  Public Overridable Property Item_Descripcion() As String
    Get
      Return Me.mItem_Descripcion
    End Get
    Set(ByVal value As String)
      Me.mItem_Descripcion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Ubicacion() As String
    Get
      Return Me.mItem_Ubicacion
    End Get
    Set(ByVal value As String)
      Me.mItem_Ubicacion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Unidadmedida() As Integer
    Get
      Return Me.mParame_Unidadmedida
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Unidadmedida = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Unidadmedida() As Integer
    Get
      Return Me.mPardet_Unidadmedida
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Unidadmedida = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Entida_Proveedor() As Integer
    Get
      Return Me.mEntida_Proveedor
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Proveedor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_CodigoAuxiliar() As String
    Get
      Return Me.mItem_CodigoAuxiliar
    End Get
    Set(ByVal value As String)
      Me.mItem_CodigoAuxiliar = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_CodigoProveedor() As String
    Get
      Return Me.mItem_CodigoProveedor
    End Get
    Set(ByVal value As String)
      Me.mItem_CodigoProveedor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_esIvaIncluido() As Boolean
    Get
      Return Me.mItem_esIvaIncluido
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_esIvaIncluido = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_esRegistroSerie() As Boolean
    Get
      Return Me.mItem_esRegistroSerie
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_esRegistroSerie = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Combo() As Boolean
    Get
      Return Me.mItem_Combo
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_Combo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_PrecioxCantidad() As Boolean
    Get
      Return Me.mItem_PrecioxCantidad
    End Get
    Set(ByVal value As Boolean)
      Me.mItem_PrecioxCantidad = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
