'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "ItemxBodega"
Partial Public Class ItemxBodega
  Inherits _Database

  Private mEmpres_Codigo As Integer = 0

  Private mItem_Codigo As Integer = 0

  Private mSucurs_Bodega As Integer = 0

  Private mBodega_Codigo As Integer = 0

  Private mItebod_Costopromedio As Decimal = 0

  Private mItebod_Cantidad As Decimal = 0

  Private mItebod_StockMinimo As Decimal = 0

  Private mItebod_StockMaximo As Decimal = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return Me.mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Codigo() As Integer
    Get
      Return Me.mItem_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mItem_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Bodega() As Integer
    Get
      Return Me.mSucurs_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Bodega_Codigo() As Integer
    Get
      Return Me.mBodega_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mBodega_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Itebod_Costopromedio() As Decimal
    Get
      Return Me.mItebod_Costopromedio
    End Get
    Set(ByVal value As Decimal)
      Me.mItebod_Costopromedio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Itebod_Cantidad() As Decimal
    Get
      Return Me.mItebod_Cantidad
    End Get
    Set(ByVal value As Decimal)
      Me.mItebod_Cantidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Itebod_StockMinimo() As Decimal
    Get
      Return Me.mItebod_StockMinimo
    End Get
    Set(ByVal value As Decimal)
      Me.mItebod_StockMinimo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Itebod_StockMaximo() As Decimal
    Get
      Return Me.mItebod_StockMaximo
    End Get
    Set(ByVal value As Decimal)
      Me.mItebod_StockMaximo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
