'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "MovimientoInventario"
Partial Public Class MovimientoInventario
  Inherits _Database

  Private mParame_Tipomovinv As Integer = 440

  Private mPardet_Tipomovinv As Integer = 1

  Private mEmpres_Bodega As Integer = 0

  Private mSucurs_Bodega As Integer = 0

  Private mMovinv_Secuencia As Integer = 0

  Private mBodega_Codigo As Integer = 0

  Private mSucurs_Bodegadestino As Integer = 0

  Private mBodega_Bodegadestino As Integer = 0

  Private mMovinv_Fecha As Date = Now.Date

  Private mMovinv_Observaciones As String = ""

  Private mSRI_iva As Integer = 0

  Private mMovinv_porcIVA As Decimal = 0

  Private mMovinv_Descto As Decimal = 0

  Private mMovinv_esAnulada As Boolean = False

  'Private mRegCtb_Secuencia As Integer = 0

  'Private mCtaCtb_Codigo As String = ""

  'Private mParame_SubCuenta As Integer = 0

  'Private mPardet_SubCuenta As Integer = 0

  Private mMovinv_autorizado As Boolean = False

  Private mItem_Codigo As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipomovinv() As Integer
    Get
      Return Me.mParame_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipomovinv() As Integer
    Get
      Return Me.mPardet_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Empres_Bodega() As Integer
    Get
      Return Me.mEmpres_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Bodega() As Integer
    Get
      Return Me.mSucurs_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Secuencia() As Integer
    Get
      Return Me.mMovinv_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mMovinv_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Bodega_Codigo() As Integer
    Get
      Return Me.mBodega_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mBodega_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Bodegadestino() As Integer
    Get
      Return Me.mSucurs_Bodegadestino
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Bodegadestino = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Bodega_Bodegadestino() As Integer
    Get
      Return Me.mBodega_Bodegadestino
    End Get
    Set(ByVal value As Integer)
      Me.mBodega_Bodegadestino = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Fecha", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Fecha, 85, True)> _
  Public Overridable Property Movinv_Fecha() As Date
    Get
      Return Me.mMovinv_Fecha
    End Get
    Set(ByVal value As Date)
      Me.mMovinv_Fecha = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  <Infoware.Reportes.CampoReporteAtributo("Hora", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 15, False)> _
  Public ReadOnly Property Hora() As String
    Get
      Return Utilerias.fechahoraservidor(OperadorDatos).ToShortTimeString
    End Get
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Observaciones() As String
    Get
      Return Me.mMovinv_Observaciones
    End Get
    Set(ByVal value As String)
      Me.mMovinv_Observaciones = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property SRI_iva() As Integer
    Get
      Return Me.mSRI_iva
    End Get
    Set(ByVal value As Integer)
      Me.mSRI_iva = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_porcIVA() As Decimal
    Get
      Return Me.mMovinv_porcIVA
    End Get
    Set(ByVal value As Decimal)
      Me.mMovinv_porcIVA = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Descto() As Decimal
    Get
      Return Me.mMovinv_Descto
    End Get
    Set(ByVal value As Decimal)
      Me.mMovinv_Descto = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_esAnulada() As Boolean
    Get
      Return Me.mMovinv_esAnulada
    End Get
    Set(ByVal value As Boolean)
      Me.mMovinv_esAnulada = value
      EsModificado = True
    End Set
  End Property

  '<XmlAttribute()> _
  'Public Overridable Property RegCtb_Secuencia() As Integer
  '  Get
  '    Return Me.mRegCtb_Secuencia
  '  End Get
  '  Set(ByVal value As Integer)
  '    Me.mRegCtb_Secuencia = value
  '    EsModificado = True
  '  End Set
  'End Property

  '<XmlAttribute()> _
  'Public Overridable Property CtaCtb_Codigo() As String
  '  Get
  '    Return Me.mCtaCtb_Codigo
  '  End Get
  '  Set(ByVal value As String)
  '    Me.mCtaCtb_Codigo = value
  '    EsModificado = True
  '  End Set
  'End Property

  '<XmlAttribute()> _
  'Public Overridable Property Parame_SubCuenta() As Integer
  '  Get
  '    Return Me.mParame_SubCuenta
  '  End Get
  '  Set(ByVal value As Integer)
  '    Me.mParame_SubCuenta = value
  '    EsModificado = True
  '  End Set
  'End Property

  '<XmlAttribute()> _
  'Public Overridable Property Pardet_SubCuenta() As Integer
  '  Get
  '    Return Me.mPardet_SubCuenta
  '  End Get
  '  Set(ByVal value As Integer)
  '    Me.mPardet_SubCuenta = value
  '    EsModificado = True
  '  End Set
  'End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_autorizado() As Boolean
    Get
      Return Me.mMovinv_autorizado
    End Get
    Set(ByVal value As Boolean)
      Me.mMovinv_autorizado = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Item_Codigo() As Integer
    Get
      Return Me.mItem_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mItem_Codigo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
