'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "MovimientoInventarioDet"
Partial Public Class MovimientoInventarioDet
  Inherits _Database

  Private mParame_Tipomovinv As Integer = 0

  Private mPardet_Tipomovinv As Integer = 0

  Private mEmpres_Bodega As Integer = 0

  Private mSucurs_Bodega As Integer = 0

  Private mMovinv_Secuencia As Integer = 0

  Private mMoinde_Secuencia As Integer = 0

  Private mItem_Codigo As Integer = 0

  Private mParame_UnidadMedida As Integer = 0

  Private mPardet_UnidadMedida As Integer = 0

  Private mMoinde_Cantidad As Decimal = 1

  Private mMoinde_Valor As Decimal = 0

  Private mMoinde_Descto As Decimal = 0

  Private mParame_UnidMedStd As Integer = 0

  Private mPardet_UnidMedStd As Integer = 0

  Private mMoinde_CantidadStd As Decimal = 0

  Private mMoinde_ValorStd As Decimal = 0

  Private mMoinde_Costo As Decimal = 0

  Private mMoinde_Aplicaiva As Boolean = True

  Private mMoinde_Descripcion As String = ""

  Private mMoinde_esDetalleCombo As Boolean = False

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipomovinv() As Integer
    Get
      Return Me.mParame_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipomovinv() As Integer
    Get
      Return Me.mPardet_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Empres_Bodega() As Integer
    Get
      Return Me.mEmpres_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Bodega() As Integer
    Get
      Return Me.mSucurs_Bodega
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Bodega = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Movinv_Secuencia() As Integer
    Get
      Return Me.mMovinv_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mMovinv_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Secuencia() As Integer
    Get
      Return Me.mMoinde_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mMoinde_Secuencia = value
      EsModificado = True
    End Set
  End Property

  '<XmlAttribute()> _
  'Public Overridable Property Item_Codigo() As Integer
  '  Get
  '    Return Me.mItem_Codigo
  '  End Get
  '  Set(ByVal value As Integer)
  '    Me.mItem_Codigo = value
  '    EsModificado = True
  '  End Set
  'End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_UnidadMedida() As Integer
    Get
      Return Me.mParame_UnidadMedida
    End Get
    Set(ByVal value As Integer)
      Me.mParame_UnidadMedida = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_UnidadMedida() As Integer
    Get
      Return Me.mPardet_UnidadMedida
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_UnidadMedida = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Cantidad() As Decimal
    Get
      Return Me.mMoinde_Cantidad
    End Get
    Set(ByVal value As Decimal)
      Me.mMoinde_Cantidad = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Valor() As Decimal
    Get
      Return Me.mMoinde_Valor
    End Get
    Set(ByVal value As Decimal)
      Me.mMoinde_Valor = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Descto() As Decimal
    Get
      Return Me.mMoinde_Descto
    End Get
    Set(ByVal value As Decimal)
      Me.mMoinde_Descto = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_UnidMedStd() As Integer
    Get
      Return Me.mParame_UnidMedStd
    End Get
    Set(ByVal value As Integer)
      Me.mParame_UnidMedStd = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_UnidMedStd() As Integer
    Get
      Return Me.mPardet_UnidMedStd
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_UnidMedStd = value
      EsModificado = True
    End Set
  End Property

  '<XmlAttribute()> _
  'Public Overridable Property Moinde_CantidadStd() As Decimal
  '  Get
  '    Return Me.mMoinde_CantidadStd
  '  End Get
  '  Set(ByVal value As Decimal)
  '    Me.mMoinde_CantidadStd = value
  '    EsModificado = True
  '  End Set
  'End Property

  '<XmlAttribute()> _
  'Public Overridable Property Moinde_ValorStd() As Decimal
  '  Get
  '    Return Me.mMoinde_ValorStd
  '  End Get
  '  Set(ByVal value As Decimal)
  '    Me.mMoinde_ValorStd = value
  '    EsModificado = True
  '  End Set
  'End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Costo() As Decimal
    Get
      Return Me.mMoinde_Costo
    End Get
    Set(ByVal value As Decimal)
      Me.mMoinde_Costo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Aplicaiva() As Boolean
    Get
      Return Me.mMoinde_Aplicaiva
    End Get
    Set(ByVal value As Boolean)
      Me.mMoinde_Aplicaiva = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_Descripcion() As String
    Get
      Return Me.mMoinde_Descripcion
    End Get
    Set(ByVal value As String)
      Me.mMoinde_Descripcion = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Moinde_esDetalleCombo() As Boolean
    Get
      Return Me.mMoinde_esDetalleCombo
    End Get
    Set(ByVal value As Boolean)
      Me.mMoinde_esDetalleCombo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
