'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas



#Region "Proveedor"
Partial Public Class Proveedor
  Inherits _Database

  Private mEntida_Codigo As Integer = 0

  Private mProvee_Visible As Boolean = True

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Entida_Codigo() As Integer
    Get
      Return Me.mEntida_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEntida_Codigo = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Activo", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Logico, 50, True)> _
  <XmlAttribute()> _
  Public Overridable Property Provee_Visible() As Boolean
    Get
      Return Me.mProvee_Visible
    End Get
    Set(ByVal value As Boolean)
      Me.mProvee_Visible = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region

