'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas
Imports Infoware.Reglas.General

#Region "TipoPagoxTipoPrecio"
Partial Public Class TipoPagoxTipoPrecio
  Inherits _Database

  Private mEmpres_Codigo As Integer = 0

  Private mSucurs_Codigo As Integer = 0

  Private mParame_TipoPago As Integer = 0

  Private mPardet_TipoPago As Integer = 0

  Private mParame_TipoPrecio As Integer = 0

  Private mPardet_TipoPrecio As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return Me.mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Codigo() As Integer
    Get
      Return Me.mSucurs_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoPago() As Integer
    Get
      Return Me.mParame_TipoPago
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoPago = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoPago() As Integer
    Get
      Return Me.mPardet_TipoPago
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoPago = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_TipoPrecio() As Integer
    Get
      Return Me.mParame_TipoPrecio
    End Get
    Set(ByVal value As Integer)
      Me.mParame_TipoPrecio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_TipoPrecio() As Integer
    Get
      Return Me.mPardet_TipoPrecio
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_TipoPrecio = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
