'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Xml
Imports System.Xml.Serialization
Imports Infoware.Reglas

#Region "TipoMovimientoInventario"
Partial Public Class TipoMovimientoInventario
  Inherits _Database

  Private mParame_Tipomovinv As Integer = 0

  Private mPardet_Tipomovinv As Integer = 0

  Private mEmpres_Codigo As Integer = 0

  Private mSucurs_Codigo As Integer = 0

  Private mTipmov_Secuencia As Integer = 0

  Private mTipmov_Seguirsecuencia As Boolean = True

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Parame_Tipomovinv() As Integer
    Get
      Return Me.mParame_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mParame_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Tipomovinv() As Integer
    Get
      Return Me.mPardet_Tipomovinv
    End Get
    Set(ByVal value As Integer)
      Me.mPardet_Tipomovinv = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Empres_Codigo() As Integer
    Get
      Return Me.mEmpres_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mEmpres_Codigo = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Sucurs_Codigo() As Integer
    Get
      Return Me.mSucurs_Codigo
    End Get
    Set(ByVal value As Integer)
      Me.mSucurs_Codigo = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Secuencia", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Numero, 100, True)> _
  <XmlAttribute()> _
  Public Overridable Property Tipmov_Secuencia() As Integer
    Get
      Return Me.mTipmov_Secuencia
    End Get
    Set(ByVal value As Integer)
      Me.mTipmov_Secuencia = value
      EsModificado = True
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Activo", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Logico, 50, True)> _
  <XmlAttribute()> _
  Public Overridable Property Tipmov_Seguirsecuencia() As Boolean
    Get
      Return Me.mTipmov_Seguirsecuencia
    End Get
    Set(ByVal value As Boolean)
      Me.mTipmov_Seguirsecuencia = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
